#!/usr/bin/env bash
# VPS security hardening + dependency setup.
# Idempotent — safe to re-run, skips already-installed components.
# Run as root: sudo bash scripts/setup-vps.sh

set -euo pipefail

# ── Config ─────────────────────────────────────────────────────────────────────
SSH_USER="ubuntu"
SSH_PORT="2222"
NODE_VERSION="20"
APP_PORTS=("3001" "5000")

# ── Helpers ────────────────────────────────────────────────────────────────────
info()  { echo -e "\n\033[1;34m==>\033[0m $*"; }
ok()    { echo -e "\033[1;32m  ✓\033[0m $*"; }
warn()  { echo -e "\033[1;33m  !\033[0m $*"; }
skip()  { echo -e "\033[0;90m  -\033[0m $* (already done)"; }
die()   { echo -e "\033[1;31m  ✗\033[0m $*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Run as root: sudo bash $0"

# ── 1. Verify SSH user and key ─────────────────────────────────────────────────
info "Checking SSH user '$SSH_USER'..."
id "$SSH_USER" &>/dev/null || die "User '$SSH_USER' does not exist."
AUTH_KEYS="/home/$SSH_USER/.ssh/authorized_keys"
[ -s "$AUTH_KEYS" ] || die "No SSH key at $AUTH_KEYS — add your public key first."
ok "User '$SSH_USER' exists with SSH key"

# ── 2. System update ───────────────────────────────────────────────────────────
info "Updating system packages..."
apt-get update -qq
apt-get upgrade -y -qq
ok "System up to date"

# ── 3. System packages ─────────────────────────────────────────────────────────
info "Installing system packages..."
apt-get install -y -qq \
    ufw fail2ban unattended-upgrades \
    curl git build-essential \
    pkg-config libssl-dev openssl \
    sqlite3 net-tools cron
ok "System packages installed"

# ── 4. Harden SSH ─────────────────────────────────────────────────────────────
info "Hardening SSH..."
if grep -q "^Port $SSH_PORT" /etc/ssh/sshd_config 2>/dev/null; then
    skip "SSH already hardened on port $SSH_PORT"
else
    cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
    cat > /etc/ssh/sshd_config <<EOF
# Hardened sshd_config — generated by setup-vps.sh
Port $SSH_PORT
AddressFamily inet

# Auth
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
ChallengeResponseAuthentication no
UsePAM yes

# Limits
MaxAuthTries 3
MaxSessions 5
LoginGraceTime 20

# Safety
AllowUsers $SSH_USER
X11Forwarding no
AllowTcpForwarding no
PrintMotd no

# Keep alive
ClientAliveInterval 300
ClientAliveCountMax 2

AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
EOF
    systemctl restart sshd
    ok "SSH hardened on port $SSH_PORT"
fi

# ── 5. UFW firewall ────────────────────────────────────────────────────────────
info "Configuring UFW..."
if ufw status | grep -q "Status: active"; then
    skip "UFW already active"
else
    ufw --force reset
    ufw default deny incoming
    ufw default allow outgoing
    ufw allow "$SSH_PORT/tcp" comment "SSH"
    for port in "${APP_PORTS[@]}"; do
        ufw allow "$port/tcp" comment "app"
    done
    ufw --force enable
    ok "UFW enabled — open ports: $SSH_PORT, ${APP_PORTS[*]}"
fi

# ── 6. Fail2ban ────────────────────────────────────────────────────────────────
info "Configuring fail2ban..."
if systemctl is-active fail2ban &>/dev/null && [ -f /etc/fail2ban/jail.local ]; then
    skip "Fail2ban already configured"
else
    cat > /etc/fail2ban/jail.local <<EOF
[DEFAULT]
bantime  = 1h
findtime = 10m
maxretry = 3
backend  = systemd

[sshd]
enabled  = true
port     = $SSH_PORT
EOF
    systemctl enable fail2ban
    systemctl restart fail2ban
    ok "Fail2ban active — 3 strikes = 1h ban"
fi

# ── 7. Auto security updates ───────────────────────────────────────────────────
info "Enabling unattended security updates..."
cat > /etc/apt/apt.conf.d/20auto-upgrades <<EOF
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";
EOF
ok "Unattended upgrades enabled"

# ── 8. Remove unwanted services ───────────────────────────────────────────────
info "Removing unwanted services..."
for svc in redis-server redis mongodb apache2; do
    if systemctl is-enabled "$svc" &>/dev/null; then
        systemctl disable --now "$svc" 2>/dev/null || true
        warn "Disabled: $svc"
    fi
done
apt-get remove --purge -y -qq redis-server redis-tools 2>/dev/null || true
apt-get autoremove -y -qq
ok "Unwanted services cleared"

# ── 9. Clean and harden /tmp ──────────────────────────────────────────────────
info "Hardening /tmp..."
find /tmp -mindepth 1 -delete 2>/dev/null || true
if grep -q '^tmpfs /tmp' /etc/fstab 2>/dev/null; then
    skip "/tmp already hardened in fstab"
else
    echo "tmpfs /tmp tmpfs defaults,noexec,nosuid,nodev 0 0" >> /etc/fstab
    mount -o remount /tmp 2>/dev/null || true
    ok "/tmp remounted noexec,nosuid,nodev"
fi

# ── 10. Node.js via nvm ───────────────────────────────────────────────────────
info "Checking Node.js..."
NVM_DIR="/home/$SSH_USER/.nvm"
if [ -d "$NVM_DIR" ] && su - "$SSH_USER" -c "export NVM_DIR=\"$NVM_DIR\" && . \"$NVM_DIR/nvm.sh\" && node --version" &>/dev/null; then
    NODE_VER=$(su - "$SSH_USER" -c "export NVM_DIR=\"$NVM_DIR\" && . \"$NVM_DIR/nvm.sh\" && node --version")
    skip "Node.js $NODE_VER already installed via nvm"
else
    su - "$SSH_USER" -c "
      set -e
      curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      export NVM_DIR=\"\$HOME/.nvm\"
      [ -s \"\$NVM_DIR/nvm.sh\" ] && . \"\$NVM_DIR/nvm.sh\"
      nvm install $NODE_VERSION
      nvm alias default $NODE_VERSION
      nvm use default
    "
    BASHRC="/home/$SSH_USER/.bashrc"
    if ! grep -q 'NVM_DIR' "$BASHRC"; then
        cat >> "$BASHRC" <<'NVMEOF'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
NVMEOF
    fi
    ok "Node.js $NODE_VERSION installed via nvm"
fi

# Symlink node/npm/npx — always refresh in case nvm version changed
NODE_BIN_DIR=$(su - "$SSH_USER" -c "export NVM_DIR=\"$NVM_DIR\" && . \"$NVM_DIR/nvm.sh\" && dirname \$(which node)")
ln -sf "$NODE_BIN_DIR/node" /usr/local/bin/node
ln -sf "$NODE_BIN_DIR/npm"  /usr/local/bin/npm
ln -sf "$NODE_BIN_DIR/npx"  /usr/local/bin/npx
ok "node/npm/npx symlinked → /usr/local/bin ($(node --version))"

# ── 11. Rust via rustup ───────────────────────────────────────────────────────
info "Checking Rust..."
CARGO_BIN="/home/$SSH_USER/.cargo/bin"
if [ -x "$CARGO_BIN/cargo" ]; then
    RUST_VER=$(su - "$SSH_USER" -c ". \"\$HOME/.cargo/env\" && cargo --version")
    skip "Rust already installed ($RUST_VER)"
else
    su - "$SSH_USER" -c "
      set -e
      curl -fsSL https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
      . \"\$HOME/.cargo/env\"
      cargo --version
    "
    ok "Rust stable installed"
fi

# Symlink the real compiled binaries (not rustup shims) so cargo works as root
TOOLCHAIN_BIN=$(su - "$SSH_USER" -c ". \"\$HOME/.cargo/env\" && dirname \$(rustup which cargo)")
ln -sf "$TOOLCHAIN_BIN/cargo" /usr/local/bin/cargo
ln -sf "$TOOLCHAIN_BIN/rustc" /usr/local/bin/rustc
CARGO_VER=$(su - "$SSH_USER" -c ". \"\$HOME/.cargo/env\" && cargo --version")
ok "cargo/rustc symlinked → /usr/local/bin ($CARGO_VER)"

# ── 12. Verify all required binaries ──────────────────────────────────────────
info "Verifying dependencies..."
ALL_OK=1
for cmd in git curl make openssl sqlite3 node npm npx cargo; do
    if command -v "$cmd" &>/dev/null; then
        ok "$cmd → $(command -v $cmd)"
    else
        warn "MISSING: $cmd"
        ALL_OK=0
    fi
done
[ "$ALL_OK" -eq 1 ] || die "Some dependencies are missing — check warnings above."

# ── 13. Check for suspicious cron jobs ────────────────────────────────────────
info "Checking cron jobs..."
for user in root "$SSH_USER"; do
    CRON=$(crontab -u "$user" -l 2>/dev/null || true)
    if [ -n "$CRON" ]; then
        warn "Cron jobs for $user — review manually:"
        echo "$CRON"
    else
        ok "No cron jobs for $user"
    fi
done

# ── 14. Summary ────────────────────────────────────────────────────────────────
VPS_IP=$(curl -s ifconfig.me 2>/dev/null || echo YOUR_VPS_IP)
info "Setup complete!"
echo ""
echo "  SSH port  : $SSH_PORT"
echo "  Open ports: $SSH_PORT (SSH) ${APP_PORTS[*]} (app)"
echo "  Node.js   : $(node --version)"
echo "  Rust      : $(cargo --version)"
echo "  sqlite3   : $(sqlite3 --version | cut -d' ' -f1)"
echo ""
echo "  Next steps:"
echo "    git clone <repo> && cd bsds-dashboard && make fresh"
echo ""
warn "Test SSH in a NEW terminal before closing this session:"
echo "  ssh -p $SSH_PORT $SSH_USER@$VPS_IP"
echo ""
