#!/usr/bin/env bash
# VPS initial security hardening script.
# Run as root on a fresh Ubuntu/Debian VPS:
#   curl -o setup-vps.sh https://... && chmod +x setup-vps.sh && sudo bash setup-vps.sh

set -euo pipefail

# ── Config ─────────────────────────────────────────────────────────────────────
SSH_USER="mojo"
SSH_PORT="2222"
APP_PORTS=("3001" "5000")   # frontend, backend

# ── Helpers ────────────────────────────────────────────────────────────────────
info()  { echo -e "\n\033[1;34m==>\033[0m $*"; }
ok()    { echo -e "\033[1;32m  ✓\033[0m $*"; }
warn()  { echo -e "\033[1;33m  !\033[0m $*"; }
die()   { echo -e "\033[1;31m  ✗\033[0m $*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Run as root: sudo bash $0"

# ── 1. System update ───────────────────────────────────────────────────────────
info "Updating system packages..."
apt-get update -qq
apt-get upgrade -y -qq
ok "System up to date"

# ── 2. Install required packages ───────────────────────────────────────────────
info "Installing ufw, fail2ban, unattended-upgrades..."
apt-get install -y -qq ufw fail2ban unattended-upgrades curl git build-essential \
    sqlite3 pkg-config libssl-dev
ok "Packages installed"

# ── 3. Verify SSH user and key exist ───────────────────────────────────────────
info "Checking SSH user '$SSH_USER'..."
if ! id "$SSH_USER" &>/dev/null; then
    die "User '$SSH_USER' does not exist. Create it first at the VPS console."
fi
AUTH_KEYS="/home/$SSH_USER/.ssh/authorized_keys"
if [ ! -s "$AUTH_KEYS" ]; then
    die "No SSH keys found at $AUTH_KEYS. Add your public key first."
fi
ok "User '$SSH_USER' exists with SSH key"

# ── 4. Harden SSH ─────────────────────────────────────────────────────────────
info "Hardening SSH (port $SSH_PORT, keys only, no root)..."
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
cat > /etc/ssh/sshd_config <<EOF
# Hardened sshd_config — generated by setup-vps.sh
Port $SSH_PORT
AddressFamily inet

# Auth
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
ChallengeResponseAuthentication no
UsePAM yes

# Limits
MaxAuthTries 3
MaxSessions 5
LoginGraceTime 20

# Safety
AllowUsers $SSH_USER
X11Forwarding no
AllowTcpForwarding no
PrintMotd no

# Keep connections alive
ClientAliveInterval 300
ClientAliveCountMax 2

AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
EOF
systemctl restart sshd
ok "SSH hardened on port $SSH_PORT"

# ── 5. UFW firewall ────────────────────────────────────────────────────────────
info "Configuring UFW..."
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow "$SSH_PORT/tcp" comment "SSH"
for port in "${APP_PORTS[@]}"; do
    ufw allow "$port/tcp" comment "app"
done
ufw --force enable
ok "UFW enabled — open ports: $SSH_PORT, ${APP_PORTS[*]}"

# ── 6. Fail2ban ────────────────────────────────────────────────────────────────
info "Configuring fail2ban..."
cat > /etc/fail2ban/jail.local <<EOF
[DEFAULT]
bantime  = 1h
findtime = 10m
maxretry = 3
backend  = systemd

[sshd]
enabled  = true
port     = $SSH_PORT
EOF
systemctl enable fail2ban
systemctl restart fail2ban
ok "Fail2ban active — 3 strikes = 1h ban"

# ── 7. Auto security updates ───────────────────────────────────────────────────
info "Enabling unattended security updates..."
cat > /etc/apt/apt.conf.d/20auto-upgrades <<EOF
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";
EOF
ok "Unattended upgrades enabled"

# ── 8. Disable and remove common unwanted services ────────────────────────────
info "Removing unwanted services..."
for svc in redis-server redis mongodb apache2 nginx; do
    if systemctl is-enabled "$svc" &>/dev/null; then
        systemctl disable --now "$svc" 2>/dev/null || true
        warn "Disabled: $svc"
    fi
done
apt-get remove --purge -y -qq redis-server redis-tools 2>/dev/null || true
apt-get autoremove -y -qq
ok "Unwanted services removed"

# ── 9. Clean /tmp ─────────────────────────────────────────────────────────────
info "Cleaning /tmp..."
find /tmp -mindepth 1 -delete 2>/dev/null || true
ok "/tmp cleaned"

# ── 10. Harden /tmp (noexec mount) ────────────────────────────────────────────
info "Mounting /tmp with noexec..."
if ! grep -q '/tmp' /etc/fstab; then
    echo "tmpfs /tmp tmpfs defaults,noexec,nosuid,nodev 0 0" >> /etc/fstab
    mount -o remount /tmp 2>/dev/null || true
    ok "/tmp remounted noexec"
else
    warn "/tmp already in fstab — skipping"
fi

# ── 11. Install Node.js (via nvm, as SSH_USER) ────────────────────────────────
info "Installing Node.js via nvm for '$SSH_USER'..."
NODE_VERSION="20"
su - "$SSH_USER" -c "
  set -e
  curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  export NVM_DIR=\"\$HOME/.nvm\"
  [ -s \"\$NVM_DIR/nvm.sh\" ] && . \"\$NVM_DIR/nvm.sh\"
  nvm install $NODE_VERSION
  nvm alias default $NODE_VERSION
  nvm use default
"
# Add nvm to .bashrc if not already there
BASHRC="/home/$SSH_USER/.bashrc"
if ! grep -q 'NVM_DIR' "$BASHRC"; then
    cat >> "$BASHRC" <<'NVMEOF'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
NVMEOF
fi
ok "Node.js $NODE_VERSION installed"

# ── 12. Install Rust (as SSH_USER) ────────────────────────────────────────────
info "Installing Rust for '$SSH_USER'..."
su - "$SSH_USER" -c "
  set -e
  curl -fsSL https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
"
ok "Rust installed"

# ── 13. Check for suspicious cron jobs ───────────────────────────────────────
info "Checking for suspicious cron jobs..."
for user in root "$SSH_USER"; do
    CRON=$(crontab -u "$user" -l 2>/dev/null || true)
    if [ -n "$CRON" ]; then
        warn "Cron jobs found for $user — review manually:"
        echo "$CRON"
    else
        ok "No cron jobs for $user"
    fi
done

# ── 14. Summary ────────────────────────────────────────────────────────────────
info "Setup complete!"
echo ""
echo "  SSH port  : $SSH_PORT"
echo "  Open ports: $SSH_PORT (SSH), ${APP_PORTS[*]} (app)"
echo "  Auth      : key-only, no root, no passwords"
echo "  Fail2ban  : 3 attempts = 1h ban"
echo "  Node.js   : v$NODE_VERSION (nvm)"
echo "  Rust      : stable (rustup)"
echo "  sqlite3   : installed"
echo ""
echo "  Next steps:"
echo "    1. git clone your repo"
echo "    2. cd into it and run: make fresh"
echo ""
warn "IMPORTANT: Test SSH in a NEW terminal before closing this session:"
echo "  ssh -p $SSH_PORT $SSH_USER@$(curl -s ifconfig.me 2>/dev/null || echo YOUR_VPS_IP)"
echo ""
