#!/usr/bin/env bash
# VPS security hardening + dependency setup.
# Idempotent — safe to re-run, skips already-installed components.
# Run as the app user (NOT root): bash scripts/setup-vps.sh

set -euo pipefail

# ── Config ─────────────────────────────────────────────────────────────────────
SSH_PORT="2222"
NODE_VERSION="20"
APP_PORTS=("3001" "5000")

# ── Helpers ────────────────────────────────────────────────────────────────────
info()  { echo -e "\n\033[1;34m==>\033[0m $*"; }
ok()    { echo -e "\033[1;32m  ✓\033[0m $*"; }
warn()  { echo -e "\033[1;33m  !\033[0m $*"; }
skip()  { echo -e "\033[0;90m  -\033[0m $* (already done)"; }
die()   { echo -e "\033[1;31m  ✗\033[0m $*" >&2; exit 1; }

[ "$(id -u)" -ne 0 ] || die "Do not run as root. Run as your app user: bash $0"
command -v sudo &>/dev/null || die "sudo is required but not installed."

SSH_USER="$(whoami)"
HOME_DIR="$HOME"

# ── 1. Verify SSH key exists ───────────────────────────────────────────────────
info "Checking SSH key for '$SSH_USER'..."
AUTH_KEYS="$HOME_DIR/.ssh/authorized_keys"
[ -s "$AUTH_KEYS" ] || die "No SSH key at $AUTH_KEYS — add your public key first."
ok "SSH key present"

# ── 2. System update (root) ────────────────────────────────────────────────────
info "Updating system packages..."
sudo apt-get update -qq
sudo apt-get upgrade -y -qq
ok "System up to date"

# ── 3. System packages (root) ──────────────────────────────────────────────────
info "Installing system packages..."
sudo apt-get install -y -qq \
    ufw fail2ban unattended-upgrades \
    curl git build-essential \
    pkg-config libssl-dev openssl \
    sqlite3 net-tools cron
ok "System packages installed"

# ── 4. Harden SSH (root) ──────────────────────────────────────────────────────
info "Hardening SSH..."
if sudo grep -q "^Port $SSH_PORT" /etc/ssh/sshd_config 2>/dev/null; then
    skip "SSH already hardened on port $SSH_PORT"
else
    sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
    sudo tee /etc/ssh/sshd_config > /dev/null <<EOF
# Hardened sshd_config — generated by setup-vps.sh
Port $SSH_PORT
AddressFamily inet

# Auth
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
ChallengeResponseAuthentication no
UsePAM yes

# Limits
MaxAuthTries 3
MaxSessions 5
LoginGraceTime 20

# Safety
AllowUsers $SSH_USER
X11Forwarding no
AllowTcpForwarding no
PrintMotd no

# Keep alive
ClientAliveInterval 300
ClientAliveCountMax 2

AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
EOF
    sudo systemctl restart sshd
    ok "SSH hardened on port $SSH_PORT"
fi

# ── 5. UFW firewall (root) ────────────────────────────────────────────────────
info "Configuring UFW..."
if sudo ufw status | grep -q "Status: active"; then
    skip "UFW already active"
else
    sudo ufw --force reset
    sudo ufw default deny incoming
    sudo ufw default allow outgoing
    sudo ufw allow "$SSH_PORT/tcp" comment "SSH"
    for port in "${APP_PORTS[@]}"; do
        sudo ufw allow "$port/tcp" comment "app"
    done
    sudo ufw --force enable
    ok "UFW enabled — open ports: $SSH_PORT, ${APP_PORTS[*]}"
fi

# ── 6. Fail2ban (root) ────────────────────────────────────────────────────────
info "Configuring fail2ban..."
if sudo systemctl is-active fail2ban &>/dev/null && [ -f /etc/fail2ban/jail.local ]; then
    skip "Fail2ban already configured"
else
    sudo tee /etc/fail2ban/jail.local > /dev/null <<EOF
[DEFAULT]
bantime  = 1h
findtime = 10m
maxretry = 3
backend  = systemd

[sshd]
enabled  = true
port     = $SSH_PORT
EOF
    sudo systemctl enable fail2ban
    sudo systemctl restart fail2ban
    ok "Fail2ban active — 3 strikes = 1h ban"
fi

# ── 7. Auto security updates (root) ───────────────────────────────────────────
info "Enabling unattended security updates..."
sudo tee /etc/apt/apt.conf.d/20auto-upgrades > /dev/null <<EOF
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";
EOF
ok "Unattended upgrades enabled"

# ── 8. Remove unwanted services (root) ────────────────────────────────────────
info "Removing unwanted services..."
for svc in redis-server redis mongodb apache2; do
    if sudo systemctl is-enabled "$svc" &>/dev/null; then
        sudo systemctl disable --now "$svc" 2>/dev/null || true
        warn "Disabled: $svc"
    fi
done
sudo apt-get remove --purge -y -qq redis-server redis-tools 2>/dev/null || true
sudo apt-get autoremove -y -qq
ok "Unwanted services cleared"

# ── 9. Clean and harden /tmp (root) ───────────────────────────────────────────
info "Hardening /tmp..."
sudo find /tmp -mindepth 1 -delete 2>/dev/null || true
if grep -q '^tmpfs /tmp' /etc/fstab 2>/dev/null; then
    skip "/tmp already hardened in fstab"
else
    echo "tmpfs /tmp tmpfs defaults,noexec,nosuid,nodev 0 0" | sudo tee -a /etc/fstab > /dev/null
    sudo mount -o remount /tmp 2>/dev/null || true
    ok "/tmp remounted noexec,nosuid,nodev"
fi

# ── 10. Node.js via nvm (as current user) ─────────────────────────────────────
info "Checking Node.js..."
NVM_DIR="$HOME_DIR/.nvm"
if [ -d "$NVM_DIR" ] && (export NVM_DIR && . "$NVM_DIR/nvm.sh" && node --version) &>/dev/null; then
    NODE_VER=$(export NVM_DIR="$NVM_DIR" && . "$NVM_DIR/nvm.sh" && node --version)
    skip "Node.js $NODE_VER already installed via nvm"
else
    curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    export NVM_DIR="$HOME_DIR/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
    nvm install "$NODE_VERSION"
    nvm alias default "$NODE_VERSION"
    nvm use default
    if ! grep -q 'NVM_DIR' "$HOME_DIR/.bashrc"; then
        cat >> "$HOME_DIR/.bashrc" <<'NVMEOF'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
NVMEOF
    fi
    ok "Node.js $NODE_VERSION installed via nvm"
fi

# Symlink node/npm/npx to /usr/local/bin (root needed for the symlink target)
export NVM_DIR="$HOME_DIR/.nvm"
. "$NVM_DIR/nvm.sh"
NODE_BIN_DIR="$(dirname "$(which node)")"
sudo ln -sf "$NODE_BIN_DIR/node" /usr/local/bin/node
sudo ln -sf "$NODE_BIN_DIR/npm"  /usr/local/bin/npm
sudo ln -sf "$NODE_BIN_DIR/npx"  /usr/local/bin/npx
ok "node/npm/npx symlinked → /usr/local/bin ($(node --version))"

# ── 11. Rust via rustup (as current user) ─────────────────────────────────────
info "Checking Rust..."
if [ -x "$HOME_DIR/.cargo/bin/cargo" ]; then
    RUST_VER=$(. "$HOME_DIR/.cargo/env" && cargo --version)
    skip "Rust already installed ($RUST_VER)"
else
    curl -fsSL https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
    . "$HOME_DIR/.cargo/env"
    ok "Rust stable installed ($(cargo --version))"
fi

# Symlink real toolchain binaries (not shims) so they work system-wide
. "$HOME_DIR/.cargo/env"
TOOLCHAIN_BIN="$(dirname "$(rustup which cargo)")"
sudo ln -sf "$TOOLCHAIN_BIN/cargo" /usr/local/bin/cargo
sudo ln -sf "$TOOLCHAIN_BIN/rustc" /usr/local/bin/rustc
ok "cargo/rustc symlinked → /usr/local/bin ($(cargo --version))"

# ── 12. Verify all required binaries ──────────────────────────────────────────
info "Verifying dependencies..."
ALL_OK=1
for cmd in git curl make openssl sqlite3 node npm npx cargo; do
    if command -v "$cmd" &>/dev/null; then
        ok "$cmd → $(command -v "$cmd")"
    else
        warn "MISSING: $cmd"
        ALL_OK=0
    fi
done
[ "$ALL_OK" -eq 1 ] || die "Some dependencies are missing — check warnings above."

# ── 13. Check for suspicious cron jobs ────────────────────────────────────────
info "Checking cron jobs..."
for user in root "$SSH_USER"; do
    CRON=$(sudo crontab -u "$user" -l 2>/dev/null || true)
    if [ -n "$CRON" ]; then
        warn "Cron jobs for $user — review manually:"
        echo "$CRON"
    else
        ok "No cron jobs for $user"
    fi
done

# ── 14. Summary ────────────────────────────────────────────────────────────────
VPS_IP=$(curl -s ifconfig.me 2>/dev/null || echo YOUR_VPS_IP)
info "Setup complete!"
echo ""
echo "  User      : $SSH_USER"
echo "  SSH port  : $SSH_PORT"
echo "  Open ports: $SSH_PORT (SSH) ${APP_PORTS[*]} (app)"
echo "  Node.js   : $(node --version)"
echo "  Rust      : $(cargo --version)"
echo "  sqlite3   : $(sqlite3 --version | cut -d' ' -f1)"
echo ""
echo "  Next steps:"
echo "    git clone <repo> && cd bsds-dashboard && make fresh"
echo ""
warn "Test SSH in a NEW terminal before closing this session:"
echo "  ssh -p $SSH_PORT $SSH_USER@$VPS_IP"
echo ""
